# a_tensor_initialization.py

In [1]:
import torch

In [2]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # t1 텐서의 타입을 출력 t1.Tensor는 기존 데이터의 타입을 출력
print(t1.device)  # t1 텐서의 디바이스 정보 출력
print(t1.requires_grad)  # t1 텐서의 자동미분 가능 여부 출력
print(t1.size())  # t1의 사이즈 출력 = torch.Size([3])
print(t1.shape)   # t1의 shape 출력 = torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # t1 텐서의 타입을 출력 t1.tensor는 데이터 타입을 지정할 수 있음
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)  

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [5]:
a1 = torch.tensor(1)			     # 1은 스칼라 이기 때문에 shape는 torch.Size([])이고 차원은 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # [1]은 벡터임으로 shape는 torch.Size([1])이고 차원은 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # [1,2,3,4,5]은 벡터임으로 shape는 torch.Size[5]이고 차원은 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape 계산 : [5,1] 차원 1
print(a4.shape, a4.ndim)

a5 = torch.tensor([               #shape 계산 : [3,2]  차원 : 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shaper계산 : [3,2,1] 차원 : 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape계산 : [3, 1, 2, 1] 차원 : 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape 계산 : [3, 1, 2, 3], 차원 : 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape 계산 : [3, 1, 2, 3, 1], 차원 : 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape 계산 : [4, 5], 차원 : 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape 계산 [4, 1, 5]), 차원 : 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


In [6]:
a11 = torch.tensor([                 # 차원과 길이가 맞지 않는 오류 발생
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

- 위 코드에서 torch.tensor() 함수는 주어진 리스트내 원소 타입을 그대로 유지시켜 준다.

# b_tensor_initialization_copy

In [6]:
import torch
import numpy as np

In [4]:
l1 = [1, 2, 3] 
t1 = torch.Tensor(l1) #l1을 tensor로 변환 torch.Tensor는 float

l2 = [1, 2, 3]
t2 = torch.tensor(l2) #torch.tensor는 int

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) #numpy배열을 변환 시 복사하지 않고 데이터를 공유하는 tensor로 변환

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1) 
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [8]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6) #데이터를 공유함으로 t6[0]값이 100으로 변환

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# c_tensor_initialization_constant_values

In [2]:
import torch

In [3]:
t1 = torch.ones(size=(5,))  # 크기가 (5,)이고 1로 채워진 텐서 생성
t1_like = torch.ones_like(input=t1) #t1과 동일한 데이터 타입과 크기를 가지고 1로 채워진 텐서 생성
print(t1)  
print(t1_like)  

t2 = torch.zeros(size=(6,))  # 크기가 (6,)이고 0으로 채워진 텐서 생성
t2_like = torch.zeros_like(input=t2)
print(t2) 
print(t2_like)  

t3 = torch.empty(size=(4,))  # 크기가 (4,)이고 값이 빈 텐서 생성
t3_like = torch.empty_like(input=t3)
print(t3)  
print(t3_like)

t4 = torch.eye(n=3) #크기가 3x3인 항등 행렬 생성
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values

In [4]:
import torch

In [5]:
t1 = torch.randint(low=10, high=20, size=(1, 2)) #범위가 10이상 20미만인 정수의 랜덤값을 가진 (1,2)크기의 텐서 생성
print(t1)

t2 = torch.rand(size=(1, 3)) #범위가 0이상 1미만의 랜덤값을 가진 텐서를 (1,3)크기로 생성
print(t2)

t3 = torch.randn(size=(1, 3)) #크기가 (1,3)이고 평균이 0이고 표준편차가 1인 정규분포에서 랜덤한 값을 가짐
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) #크기가 (3,2)이고 평균이 10.0이면서 표준편차가 1.0인 정규분포에서 랜덤한 값을 가진 텐서 생성
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3) #start값과 end값 사이에서 steps간격의 값을 가진 텐서 생성
print(t5)

t6 = torch.arange(5) #0부터 5까지의 정수 값을 갖진 텐서 생성
print(t6)

tensor([[13, 18]])
tensor([[0.6511, 0.4423, 0.5787]])
tensor([[ 0.0932, -1.0211, -1.6431]])
tensor([[11.8241,  9.3969],
        [11.9216, 11.5374],
        [ 8.6776, 12.5681]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [20]:
torch.manual_seed(1729) #난수 생성 과정에서 동일한 시드는 동일한 값을 가짐
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

In [6]:
import torch

In [7]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16) #int로 타입 변경
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20. #float64로 타입 변경
print(c)

d = b.to(torch.int32) #b의 타입을 int32로 변경
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 6.5782, 16.7077, 12.8093],
        [ 4.3799,  9.2938, 10.3018]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [8]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64
torch.int16
torch.float64


# f_tensor_operations

In [9]:
import torch


In [11]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2) #t1+t2(요소별 접근) 식을 나타내는 코드
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [12]:
t5 = torch.sub(t1, t2) #t1-t2(요소별 접근)식을 나타내는 코드
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
t7 = torch.mul(t1, t2) #t1*t2
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
t9 = torch.div(t1, t2) #t1/t2
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

In [15]:
import torch

In [18]:
t1 = torch.dot( #두 1차원 벡터의 내적을 계산 (2*2)+(3*1)=7
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size()) #사이즈는 스칼라값

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) #두 2차원 행렬의 곱셈값을 저장
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) #두 3차원 행렬의 행렬 곱셈값 저장
print(t7.size())

tensor(7) torch.Size([])
tensor([[ 0.7437,  0.7512],
        [ 0.1400, -0.9386]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


# h_tensor_operations_matmul

In [19]:
import torch

In [21]:
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # 두 1차원 텐서의 행렬곱셈의 곱셈값 저장, size는 스칼라값

t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # t4가 [3,4],로 broadcasting됨

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # r6가 (10,3,4)로 broadcasting됨

t7 = torch.randn(10, 3, 4)          #이 부분이 왜 10,3,5가 나오는지 이해를 하지 못했다.
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  

t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size()) #이 부분이 왜 10,3,5가 나오는지 이해를 하지 못했다.

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


# i_tensor_broadcasting

In [22]:
import torch

In [27]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) #원소별 곱셈

tensor([2., 4., 6.])


In [28]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) #t4가 [[4,5],[4,5],[4,5]] broadcasting됨

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [29]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  #[[2.0,2.0],[2.0, 2.0]] broadcasting
print(t5 - 2.0)  
print(t5 * 2.0) 
print(t5 / 2.0)  

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [30]:
def normalize(x): #정규화 함수
  return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [31]:
t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])  
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7]) 
print(t7 + t8)   # t8 [[3,1],[3,1]] broadcasting
print(t7 + t9)   # t9 [[5,5],[2,2]] broadcasting
print(t8 + t9)   # t8 [[3,1],[3,1]] broadcasting, t9 [[5,5],[2,2]] broadcasting
print(t7 + t10)  # t10[[7,7],[7,7]] broadcasting

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [32]:
t11 = torch.ones(4, 3, 2)    
t12 = t11 * torch.rand(3, 2) # 작은 텐서가 더 큰 텐서에 따라 broadcast  
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  
print((t17 + t18).size())

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [33]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # 작은 텐서가 더 큰 텐서에 따라 broadcast  

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size()) # 작은 텐서가 더 큰 텐서에 따라 broadcast  

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size()) # 작은 텐서가 더 큰 텐서에 따라 broadcast  

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size()) #에러 발생 t26의 3값이 t25의 2보다 크기 때문


torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [34]:
t27 = torch.ones(4) * 5
print(t27)  

t28 = torch.pow(t27, 2)
print(t28)  # t27의 값들을 제곱한 값

exp = torch.arange(1., 5.) 
a = torch.arange(1., 5.)  
t29 = torch.pow(a, exp) #밑을 a값 exp값을 지수로 계산한 값 저장
print(t29) 

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing

In [25]:
import torch

In [35]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # 1열의 행 값 저장
print(x[:, 1])  # 1행의 모든 열 값 저장
print(x[1, 2])  # X[1,2]값 저장
print(x[:, -1])  # 마지막 행의 모든 열 값 저장

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [54]:
print(x[1:])  # 1열부터 마지막 열까지 모든 행값 저장
print(x[1:, 3:])  #1열부터 마지막열과 3행부터 마지막행까지의 모든 값들 저장

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [55]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [56]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping

In [36]:
import torch

In [37]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  #[3,2]의 크기로 reshape
t3 = t1.reshape(1, 6)  # [1,6]으로 크기 reshape
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # [2,4] 크기로 reshape하고 0~7값 채움
t5 = torch.arange(6).view(2, 3)  # [2,3] 크기로 reshape하고 0~5값 채움
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [38]:
t6 = torch.tensor([[[1], [2], [3]]])

t7 = t6.squeeze()  # 크기가 1인 차원 제거

t8 = t6.squeeze(0)  # 크기가 0인 차원 제거
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [39]:
t9 = torch.tensor([1, 2, 3])

t10 = t9.unsqueeze(1)  # 크기가 1인 차원 추가로 생성
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1) 
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [40]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t14 = t13.flatten()  # 1차원 텐서로 reshape

print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1) #두 번째 차원부터 reshape

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [41]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  
print(torch.permute(t18, (2, 0, 1)).size())  # 차원 순서를 변경

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t20 = torch.permute(t19, dims=(0, 1))  # 변경x
t21 = torch.permute(t19, dims=(1, 0))  # (3,2)로 차원 변경
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # 차원을 전치

print(t22)

t23 = torch.t(t19) 

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat

In [42]:
import torch

In [66]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) #dim=1이므로 두번째 차원을 기준으로 결합
print(t4.shape)

torch.Size([2, 6, 3])


In [67]:
t5 = torch.arange(0, 3)  
t6 = torch.arange(3, 8)  

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # 첫번쨰 차원을 기준으로 결합 둘다 1차원
print(t7)  


torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [43]:
t8 = torch.arange(0, 6).reshape(2, 3)  
t9 = torch.arange(6, 12).reshape(2, 3)  


t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # 첫번째 차원을 기준으로 결합 [4,3]
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # 두번째 차원을 기준으로 결합 [2,6]
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [44]:
t12 = torch.arange(0, 6).reshape(2, 3)  
t13 = torch.arange(6, 12).reshape(2, 3)  
t14 = torch.arange(12, 18).reshape(2, 3)  

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # [6,3]
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # [2,9]
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [45]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # [2, 2, 3]
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # [1, 4, 3]
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # [1, 2, 6]
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking

In [46]:
import torch

In [74]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0) #두 텐서를 0번째 인덱스 차원을 추가하여 결합
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [47]:
t9 = torch.arange(0, 3)  #
t10 = torch.arange(3, 6)  

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# n_tensor_vstack_hstack

In [48]:
import torch

In [49]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2)) #수직 결합
print(t3)


t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9.shape)

print(t9)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [50]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) #수평으로 결합
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14)) #수평 결합 [[1,4],[2,5][3,6]]
print(t15)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제 후기

평소에 numpy를 자주 사용했는데 tensor는 numpy와 많이 비슷하다. 하지만 딥러닝에서는 모델의 학습 과정에서 오래 걸리기 때문에 gpu를 사용하기 위해 Pytorch의 tensor를 사용한다는 것을 알았다.

tensor의 shape를 계산하는 과정에서 고차원으로 가면 많이 복잡했는데 대괄호를 기준으로 개수를 세는 방법을 이용하니 쉽게 파악할 수 있었다.

tensor에서 원소별 곱셈, 내적, 행렬의 곱셈은 이미 알고 있던 부분이였는지 쉽게 했다. 

가장 많이 알게된 부분은 broadcasting과 cat에 대해 실습을 통해 어떠한 방식으로 broadcasting과 cat되는지 완벽히 이해를 했다.